branches:
  only:
  - master

sudo: required

services:
- docker

install:
- curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.20.0/skaffold-linux-amd64
- chmod +x skaffold
- sudo mv skaffold /usr/local/bin

cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script: echo "This should be running tests for continuous integration"

# Deploy  to Google Kubernetes Engine
after_success:
<<<<<<< HEAD
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "5sr-leave-a-rating-to-a-product" ]; then ./deploy.sh; fi
=======
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
>>>>>>> 5sr-leave-a-comment-to-a-product
