# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fivestarratingservice
spec:
  selector:
    matchLabels:
      app: fivestarratingservice
  template:
    metadata:
      labels:
        app: fivestarratingservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: fivestarratingservice
        ports:
        - name: grpc
          containerPort: 3333
        env:
        - name: PORT
          value: "3333"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3333"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3333"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fivestarratingservice
spec:
  type: ClusterIP
  selector:
    app: fivestarratingservice
  ports:
  - name: grpc
    port: 3333
    targetPort: 3333
